src/Entity/Mission.php
<?php

namespace App\Entity;

use App\Repository\MissionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MissionRepository::class)
 */
class Mission
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $notes;

    /**
     * @ORM\ManyToOne(targetEntity=Ville::class, inversedBy="missions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $destination;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="missions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $just_heb;

    /**
     * @ORM\ManyToOne(targetEntity=Hebergement::class, inversedBy="missions")
     */
    private $hebergement;

    /**
     * @ORM\Column(type="boolean")
     */
    private $etat;

    /**
     * @ORM\ManyToOne(targetEntity=Transport::class, inversedBy="missions")
     */
    private $transport;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prx_transport;

    public function __construct()
    {
        $this->justification = new ArrayCollection();
        $this->deplacements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): self
    {
        $this->notes = $notes;

        return $this;
    }

    public function getDestination(): ?Ville
    {
        return $this->destination;
    }

    public function setDestination(?Ville $destination): self
    {
        $this->destination = $destination;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getJustHeb(): ?string
    {
        return $this->just_heb;
    }

    public function setJustHeb(?string $just_heb): self
    {
        $this->just_heb = $just_heb;

        return $this;
    }

    public function getHebergement(): ?Hebergement
    {
        return $this->hebergement;
    }

    public function setHebergement(?Hebergement $hebergement): self
    {
        $this->hebergement = $hebergement;

        return $this;
    }

    public function getEtat(): ?bool
    {
        return $this->etat;
    }

    public function setEtat(bool $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getTransport(): ?Transport
    {
        return $this->transport;
    }

    public function setTransport(?Transport $transport): self
    {
        $this->transport = $transport;

        return $this;
    }

    public function getPrxTransport(): ?float
    {
        return $this->prx_transport;
    }

    public function setPrxTransport(?float $prx_transport): self
    {
        $this->prx_transport = $prx_transport;

        return $this;
    }
}

src/Controller/ComptableController.php
<?php

namespace App\Controller;

use App\Entity\Mission;
use App\Repository\MissionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ComptableController extends AbstractController
{
    /**
     * @Route("/comptable", name="app_gsb_comptable_accueil", methods={"GET"})
     */ 
    public function index(MissionRepository $missionRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        // $missions = $missionRepository->findBy(['etat' => 0]);
        $missions = $missionRepository->findAll();
        return $this->render('comptable/index.html.twig', [
            'user' => $this->getUser(),
            'missions' => $missions
        ]);
    }

    /**
     * @Route("/comptable/{id}/show", name="app_gsb_comptable_afficher", requirements={"id"="\d+"})
     */
    public function show(Mission $mission): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $user = $this->getUser();
        return $this->render('comptable/show.html.twig', [
            'mission' => $mission,
            'user' => $user
        ]);
    }

    /**
     * @Route("/comptable/{id}/validate", name="app_gsb_comptable_valider", requirements={"id"="\d+"}, methods={"GET", "PUT"})
     */
    public function validate(MissionRepository $missionRepository, $id, Request $request, EntityManagerInterface $manager): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $mission = $missionRepository->find($id);
        $mission->setEtat(1);
        $manager->persist($mission);
        $manager->flush();

        return $this->redirectToRoute('app_gsb_comptable_accueil');
    }
}

templates/comptable/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page Comptable
{% endblock %}

{% block body %}
	<p>Connecté en tant que
		{{ user.nom }}
		{{ user.prenom }}<a href="{{ path('app_gsb_profil', {'id' : user.id}) }}" class="btn btn-primary">Profil</a>
		<a href="{{ path('app_gsb_logout') }}" class="btn btn-primary">Déconnexion</a>
	</p>

	<table class="table">
		<tr class="table-primary">
			<td>ID</td>
			<td>Visiteur</td>
			<td>Libelle</td>
			<td>Destination</td>
			<td>Date</td>
		</tr>
		{% for mission in missions %}
			{% if mission.etat == 0 %}
				<tr>
					<td>{{ mission.id }}</td>
					<td>{{ mission.user.nom }}
						{{ mission.user.prenom }}</td>

					<td>{{ mission.libelle }}</td>
					<td>{{ mission.destination.nom }}</td>
					<td>{{ mission.dateDebut | date('d/m/Y') }}</td>
					<td>
						<a class="btn btn-secondary" href="{{ path('app_gsb_comptable_afficher', {'id' : mission.id}) }}">Afficher</a>
					</td>
				</tr>
			{% endif %}
		{% endfor %}
	</table>

{% endblock %}

templates/comptable/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Detail Mission n°{{ mission.id }}
{% endblock %}

{% block body %}
	<p>Connecté en tant que
		{{ user.nom }}
		{{ user.prenom }}<a href="{{ path('app_gsb_profil', {'id' : user.id}) }}" class="btn btn-primary">Profil</a>
		<a href="{{ path('app_gsb_logout') }}" class="btn btn-primary">Déconnexion</a>
	</p>
	<div class="d-flex align-items-center justify-content-center flex-column">
		<p><b>ID</b></p>
		<p>{{ mission.id }}</p>
		<p><b>Libelle</b></p>
		<p>{{ mission.libelle }}</p>
		<p><b>Destination</b></p>
		<p>{{ mission.destination.nom }}</p>
		<p><b>Date Début</b></p>
		<p>{{ mission.dateDebut | date('d/m/Y') }}</p>
		<p><b>Date de Fin</b></p>
		<p>{{ mission.dateFin | date('d/m/Y') }}</p>
		<p><b>Transport</b></p>
		<p>{{ mission.transport ? mission.transport.libelle }}</p>
		<p><b>Montant Transport</b></p>
		<p>{{ mission.prxTransport }}</p>
		<p><b>Hebergement</b></p>
		<p>{{ mission.hebergement ? mission.hebergement.libelle }}</p>
		<p><b>Justification</b></p>
		<p>{{ mission.justHeb }}</p>
		<p><b>Notes</b></p>
		<p>{{ mission.notes }}</p>
		<form action="{{ path('app_gsb_comptable_valider', {'id': mission.id}) }}" method="put" style="display: inline-block">
			<input type="hidden" name="_method" value="put">
			<input type="submit" value="Valider" class="btn btn-success">
		</form>
	</div>

{% endblock %}